#pragma once

enum EntityQuality {
  INVALID_QUALITY = -1,
  QUALITY_NORMAL,
  QUALITY_GENUINE,
  QUALITY_VINTAGE,
  QUALITY_UNUSUAL,
  QUALITY_COMMUNITY = 5,
  QUALITY_DEVELOPER,
  QUALITY_SELF_MADE,
  QUALITY_CUSTOMIZED,
  QUALITY_STRANGE,
  QUALITY_COMPLETED,
  QUALITY_TOURNAMENT = 12,
};